### ISSUE TITLE
Invalid MAC Address on IP:3190 load.

### ISSUE THREAD

**Issue by smdion** [mdlayher/unifi_exporter#15]
An error has occurred:

error collecting metric Desc{fqName: "unifi_stations", help: "Total number of stations (clients)", constLabels: {}, variableLabels: [site]}: invalid MAC address

Controller v5.3.7.  What version on your running?

**Comment by mdlayher** [comment]
5.0.7 here.  Also I only have APs, no switches or unifi gateways, etc.  What devices are you running?

**Comment by smdion** [comment]
I have one AP, 1 USG, and 1 8 port PoE Switch and running 5.3.7. That could be why.

**Comment by mdlayher** [comment]
That would be my guess.  I can look into relaxing some of the restrictions in my UniFi package, but because I only one APs, I don't know what data is present or not present for switches or the USG.

**Comment by smdion** [comment]
Whatever you can do that won't break your existing setup I would appreciate!

**Comment by zo1db3rg23** [comment]
I also came across this issue when using the compiled unifi_exporter.  So I manually downloaded all of the go dependencies and compiled it myself and no longer get that error.  Not sure if this helps, but I hope it does.

**Comment by mdlayher** [comment]
Good news, I ordered a Unifi Switch 8, so I'll probably be able to look into this again soon.

**Comment by stephenbock** [comment]
I'm running v5.3.10 and i just added a UniFi Switch 8 POE-150W and i'm getting the same error.

**Comment by mdlayher** [comment]
I just got mine installed a couple days ago but haven't had free time to dig into this yet.  If anyone would like to submit a PR in the meantime to get just AP metrics working with a Unifi switch/USG present, I'd be super grateful.

**Comment by mdlayher** [comment]
https://github.com/mdlayher/unifi_exporter/issues/15#issuecomment-269013458

^ It would appear that this is fixed, and I forgot about it.  I haven't done another "release" because I really only expect them to be used for my personal config management stuff.

I'll do one now though, as a stop-gap, for anyone who doesn't have Go installed locally.

**Comment by stephenbock** [comment]
That would be great.  Thanks!

**Comment by mdlayher** [comment]
Just published: https://github.com/mdlayher/unifi_exporter/releases/tag/0.4.0.

Appears to work for me.  I will need to revamp my UniFi client package and then probably do some cleanup on the exporter later on as well.

Closing this issue for now.  Feel free to file a new one if 0.4.0 is broken.
