### ISSUE TITLE
Error with Unifi 5.5.8

### ISSUE THREAD

**Issue by stephenbock** [mdlayher/unifi_exporter#19]
I'm getting the following error after upgrading the controller to 5.5.8

`[ERROR] failed collecting device metric Desc{fqName: "unifi_devices", help: "Total number of devices", constLabels: {}, variableLabels: [site]}: json: cannot unmarshal number 3.733721026E9 into Go value of type int64`

**Comment by mdlayher** [comment]
Hi, I am AFK for a couple of weeks, but if I had to guess, the controller started returning a floating point value for something that may have previously been an integer.

The fix would need to happen in package unifi, and then the vendored copy would need to be updated here. PRs welcome of course.

**Comment by eremid** [comment]
Hello,

Can you update your vendor directory please ? Your [FIX](https://github.com/mdlayher/unifi/commit/dbb64f423dd209b0b49ec4dad73788d3d9a47030) in package unifi fix this issue.

Thanks !
