### ISSUE TITLE
Trouble building

### ISSUE THREAD

**Issue by jtd5048** [mdlayher/unifi_exporter#20]
This is likely purely because I'm new to building and go, but I'm getting tripped up on building from this project. I've cloned the project, but when I use `make` I'm getting this:

```
sysadmin@prometheus-srv:~/docker/unifi_exporter$ make
go build ./cmd/unifi_exporter
cmd/unifi_exporter/main.go:13:2: cannot find package "github.com/mdlayher/unifi" in any of:
	/usr/local/go/src/github.com/mdlayher/unifi (from $GOROOT)
	/home/sysadmin/work/src/github.com/mdlayher/unifi (from $GOPATH)
cmd/unifi_exporter/main.go:14:2: cannot find package "github.com/mdlayher/unifi_exporter" in any of:
	/usr/local/go/src/github.com/mdlayher/unifi_exporter (from $GOROOT)
	/home/sysadmin/work/src/github.com/mdlayher/unifi_exporter (from $GOPATH)
cmd/unifi_exporter/main.go:15:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
	/usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
	/home/sysadmin/work/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1
```

would you mind helping out a newer user on what I'm missing here?

**Comment by mdlayher** [comment]
If I had to guess, you probably did a `git clone` instead of a `go get`?

Try `go get -d -u -v github.com/mdlayher/unifi_exporter` and then build.  This will show you that it's fetching and updating all dependencies as well.

**Comment by Kalloritis** [comment]
Even given that, this does not compile currently.

`# GOPATH=/opt/unifi_exporter/unifi_exporter/ make
go build ./cmd/unifi_exporter
# github.com/mdlayher/unifi
../unifi/client.go:102: undefined: http.MethodPost
../unifi/client.go:126: undefined: http.MethodPost
# github.com/prometheus/client_golang/prometheus
../../prometheus/client_golang/prometheus/registry.go:399: syntax error: unexpected range, expecting {
../../prometheus/client_golang/prometheus/registry.go:513: non-declaration statement outside function body
../../prometheus/client_golang/prometheus/registry.go:514: non-declaration statement outside function body
../../prometheus/client_golang/prometheus/registry.go:515: syntax error: unexpected }
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 2
# go version
go version go1.3.3 linux/amd64
`

**Comment by mdlayher** [comment]
The current stable release of Go is 1.8.1.  I don't support any versions of Go that are older than that.

Closing this issue due to lack of response from the original author.

**Comment by Kalloritis** [comment]
@mdlayher Please add a min version of Go to the readme to ensure this does not happen to others. Go 1.3.3 is the latest release that is part of the Debian 8 repo.
