### ISSUE TITLE
Automated build on Docker Hub

### ISSUE THREAD

**Issue by cmsj** [mdlayher/unifi_exporter#26]
Hey

I was just wondering if you'd be willing to set up an automated build on hub.docker.com for this repo :)

There are a few people who have forked the repo and set up their own builds, but that relies on them pulling in circles from here.

Cheers,
Chris

**Comment by mdlayher** [comment]
I've never done it myself but I have no qualms with doing it if someone sends a PR!

**Comment by mdlayher** [comment]
I'd love the help if you're willing to provide it. I'm afraid I don't have much time to keep up with this project at the moment.

**Comment by cmsj** [comment]
@mdlayher with these changes merged, would you be able to create an automated build at hub.docker.com?
