### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by yosefy** [mdlayher/unifi_exporter#3]
failed to authenticate to UniFi Controller: expected "application/json;charset=UTF-8" content type, but received "application/json"

thanks

**Comment by mdlayher** [comment]
Should be an easy fix.  Out of curiosity, what version of the UniFi controller are you running?  It works as-is for me on v5.0.6.

**Comment by yosefy** [comment]
hi
its
2.4.6
:(

but
may be you could add this option?

thanks anyway :)

**Comment by mdlayher** [comment]
I can give it a shot in my `unifi` package, but I would guess that the APIs have changed pretty dramatically between the version you're running and the newer versions.

**Comment by yosefy** [comment]
hmm.. i think you are right
i guess we need to upgrade

i will update when done
so don’t bother ( better write another exporter :)
thanks

**Comment by mdlayher** [comment]
Sounds good!

**Comment by mdlayher** [comment]
Any luck with this?

**Comment by yosefy** [comment]
hmm it will take some time to arrange :)

**Comment by mdlayher** [comment]
Going to close this out.  I imagine this Unifi controller is too old for me to be able to help out in any effective way with these packages.
