### ISSUE TITLE
password should not be configured on command line

### ISSUE THREAD

**Issue by jcollie** [mdlayher/unifi_exporter#6]
When the password is specified on the command like it's very easy for unprivileged users to see the password. A config file should be used for at least the password, and it'd be nice to be able to use a config file for the other options as well.

**Comment by mdlayher** [comment]
Makes sense to me.  I went with flags for ease of use but I can understand your point.

Should be easy enough to add something like `-unifi.config.file ~/.config/unifiexporter.yml` or something.

Would environment variables also be acceptable?

**Comment by jcollie** [comment]
Having the password in an environment variable is a little better, but still problematic is that the environment variable might need to be initialized somewhere (like a systemd unit file) that is world readable. In a config file is the best option, until Ubiquity offers an alternative like OAuth.

**Comment by mbrgm** [comment]
Would you be fine with having an INI file (using https://github.com/go-ini/ini)? If yes, then I would take a shot at creating a PR.

**Comment by mtanatwine** [comment]
Funny you should post that @mbrgm - I've just finished creating support for a yaml configuration file and am about to submit a PR. I've never worked on Go before but it works and it's relatively tidy, so feel free to critique it.

**Comment by mbrgm** [comment]
@mtanatwine See my comments. I took the 'critique' part seriously, but everything I mentioned is very pedantic. Just thought I'd take the time to go through it thoroughly. Thanks! :)

**Comment by dichro** [comment]
spf13/viper is a good drop-in option for managing config files with command-line and/or environment overrides (although it's far from drop-in, tbh).

**Comment by mbrgm** [comment]
@dichro That's right, but I think for this project it might be overkill. @mtanatwine 's PR does the job fine imho.

**Comment by mbrgm** [comment]
I think this can be closed, now that https://github.com/mdlayher/unifi_exporter/pull/37 has been merged, right?
