### ISSUE TITLE
information about client signal strengths

### ISSUE THREAD

**Issue by bbrendon** [mdlayher/unifi_exporter#7]
Would be nice if this was exposed. (enhancement)

**Comment by mdlayher** [comment]
Should be easy enough.  That work will need to occur in package `unifi`, and then we can expose it here.

**Comment by mdlayher** [comment]
Added in 0.3.0.  Should work as expected!

**Comment by mdlayher** [comment]
From a bit of Googling, looks like this calculation is what you'd want for Signal to Noise ratio.

```
(-1*unifi_stations_rssi_dbm) - unifi_stations_noise_dbm
```

```
o 40dB+ SNR =            Excellent signal
o 25dB to 40dB SNR = Very good signal
o 15dB to 25dB SNR = Low signal
o 10dB to 15dB SNR = Very low signal
o 5dB to 10dB SNR =   No signal
```

**Comment by bbrendon** [comment]
Based on some googling, I believe that calculates the SNR Margin
http://www.speedguide.net/faq/how-to-read-rssisignal-and-snrnoise-ratings-440

I did try comparing the values saved in prometheus to the unifi console and they were close, but I never saw them being the same. I'm not sure if its a timing thing or Unifi uses some adjustment factor.

**Comment by mdlayher** [comment]
Yeah, I noticed the same regarding slight differences in the values.

Which query did you end up using?  There is probably a better way than the one I provided.

**Comment by bbrendon** [comment]
I started with your query, changed some things, decided I didn't like it and went back to yours :)

I was going to try and calculating some kind of signal percentage but figured I'd collect more data since my numbers weren't matching up. Also probably research on the unifi forums why they might not be matching.

**Comment by akramer** [comment]
FWIW, it looks like Unifi 5.2.9 exports a per-station "signal" quality in negative dbm. That's probably the single-gauge signal strength metric you want.
